// megafunction wizard: %LPM_MULT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: lpm_mult 

// ============================================================
// File Name: IP_int14multint16.v
// Megafunction Name(s):
// 			lpm_mult
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.0.0 Build 156 04/24/2013 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//lpm_mult DEVICE_FAMILY="Stratix III" LPM_REPRESENTATION="SIGNED" LPM_WIDTHA=14 LPM_WIDTHB=16 LPM_WIDTHP=32 MAXIMIZE_SPEED=9 dataa datab result
//VERSION_BEGIN 13.0 cbx_cycloneii 2013:04:24:18:08:47:SJ cbx_lpm_add_sub 2013:04:24:18:08:47:SJ cbx_lpm_mult 2013:04:24:18:08:47:SJ cbx_mgl 2013:04:24:18:11:10:SJ cbx_padd 2013:04:24:18:08:47:SJ cbx_stratix 2013:04:24:18:08:47:SJ cbx_stratixii 2013:04:24:18:08:47:SJ cbx_util_mgl 2013:04:24:18:08:47:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = dsp_18bit 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  IP_int14multint16_mult
	( 
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   [13:0]  dataa;
	input   [15:0]  datab;
	output   [31:0]  result;

	wire  [29:0]   wire_mac_mult2_dataout;
	wire  [71:0]   wire_mac_out1_dataout;
	wire aclr;
	wire clken;
	wire clock;

	stratixiii_mac_mult   mac_mult2
	( 
	.aclr({4{aclr}}),
	.clk({4{clock}}),
	.dataa({dataa}),
	.datab({datab}),
	.dataout(wire_mac_mult2_dataout),
	.ena({4{clken}}),
	.scanouta(),
	.signa(1'b1),
	.signb(1'b1)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_mult2.dataa_width = 14,
		mac_mult2.datab_width = 16,
		mac_mult2.lpm_type = "stratixiii_mac_mult";
	stratixiii_mac_out   mac_out1
	( 
	.aclr({4{aclr}}),
	.clk({4{clock}}),
	.dataa({wire_mac_mult2_dataout[29:0]}),
	.dataout(wire_mac_out1_dataout),
	.dftout(),
	.ena({4{clken}}),
	.loopbackout(),
	.overflow(),
	.saturatechainoutoverflow(),
	.signa(1'b1),
	.signb(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.chainin({1{1'b0}}),
	.datab({1{1'b0}}),
	.datac({1{1'b0}}),
	.datad({1{1'b0}}),
	.rotate(1'b0),
	.round(1'b0),
	.roundchainout(1'b0),
	.saturate(1'b0),
	.saturatechainout(1'b0),
	.shiftright(1'b0),
	.zeroacc(1'b0),
	.zerochainout(1'b0),
	.zeroloopback(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		mac_out1.dataa_width = 30,
		mac_out1.dataout_width = 72,
		mac_out1.operation_mode = "output_only",
		mac_out1.lpm_type = "stratixiii_mac_out";
	assign
		aclr = 1'b0,
		clken = 1'b1,
		clock = 1'b0,
		result = {{2{wire_mac_out1_dataout[29]}}, wire_mac_out1_dataout[29:0]};
endmodule //IP_int14multint16_mult
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module IP_int14multint16 (
	dataa,
	datab,
	result)/* synthesis synthesis_clearbox = 1 */;

	input	[13:0]  dataa;
	input	[15:0]  datab;
	output	[31:0]  result;

	wire [31:0] sub_wire0;
	wire [31:0] result = sub_wire0[31:0];

	IP_int14multint16_mult	IP_int14multint16_mult_component (
				.dataa (dataa),
				.datab (datab),
				.result (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: AutoSizeResult NUMERIC "0"
// Retrieval info: PRIVATE: B_isConstant NUMERIC "0"
// Retrieval info: PRIVATE: ConstantB NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix III"
// Retrieval info: PRIVATE: LPM_PIPELINE NUMERIC "0"
// Retrieval info: PRIVATE: Latency NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SignedMult NUMERIC "1"
// Retrieval info: PRIVATE: USE_MULT NUMERIC "1"
// Retrieval info: PRIVATE: ValidConstant NUMERIC "0"
// Retrieval info: PRIVATE: WidthA NUMERIC "14"
// Retrieval info: PRIVATE: WidthB NUMERIC "16"
// Retrieval info: PRIVATE: WidthP NUMERIC "32"
// Retrieval info: PRIVATE: aclr NUMERIC "0"
// Retrieval info: PRIVATE: clken NUMERIC "0"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: PRIVATE: optimize NUMERIC "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_HINT STRING "MAXIMIZE_SPEED=9"
// Retrieval info: CONSTANT: LPM_REPRESENTATION STRING "SIGNED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_MULT"
// Retrieval info: CONSTANT: LPM_WIDTHA NUMERIC "14"
// Retrieval info: CONSTANT: LPM_WIDTHB NUMERIC "16"
// Retrieval info: CONSTANT: LPM_WIDTHP NUMERIC "32"
// Retrieval info: USED_PORT: dataa 0 0 14 0 INPUT NODEFVAL "dataa[13..0]"
// Retrieval info: USED_PORT: datab 0 0 16 0 INPUT NODEFVAL "datab[15..0]"
// Retrieval info: USED_PORT: result 0 0 32 0 OUTPUT NODEFVAL "result[31..0]"
// Retrieval info: CONNECT: @dataa 0 0 14 0 dataa 0 0 14 0
// Retrieval info: CONNECT: @datab 0 0 16 0 datab 0 0 16 0
// Retrieval info: CONNECT: result 0 0 32 0 @result 0 0 32 0
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL IP_int14multint16_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
